import { Noto_Sans, Epilogue } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import HeaderWrapper from "@/components/header/HeaderWrapper";
import Footer from "@/components/footer/Footer";
const notoSans = Noto_Sans({
   variable: "--font-noto-sans",
   subsets: ["latin"],
});

const epilogue = Epilogue({
   variable: "--font-epilogue",
   subsets: ["latin"],
});

export const metadata = {
   title: "RL Études - Bureau d'études près de Colmar",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="fr">
         <body
            className={`${notoSans.variable} ${epilogue.variable} antialiased`}
            suppressHydrationWarning={true}
         >
            <ViewTransitions>
               <HeaderWrapper />
               <main style={{ viewTransitionName: "main" }}>{children}</main>
               <Footer style={{ viewTransitionName: "footer" }} />
            </ViewTransitions>
         </body>
      </html>
   );
}
