import { Noto_Sans, Epilogue } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/header/Topbar";
import NavBar from "@/components/header/NavBar";
import FooterWrapper from "@/components/footer/FooterWrapper";
const notoSans = Noto_Sans({
   variable: "--font-noto-sans",
   subsets: ["latin"],
});

const epilogue = Epilogue({
   variable: "--font-epilogue",
   subsets: ["latin"],
});

export const metadata = {
   title: "RL Études - Bureau d'études près de Colmar",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="fr">
         <body
            className={`${notoSans.variable} ${epilogue.variable} antialiased`}
            suppressHydrationWarning={true}
         >
            <header>
               <Topbar />
               <NavBar />
            </header>
            {children}
            <FooterWrapper />
         </body>
      </html>
   );
}
